import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#da1e28',
    paddingVertical: 24,
    paddingHorizontal: 32,
    marginVertical: 8,
    marginHorizontal: 16,
    minHeight: 96,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
    position: 'relative',
    overflow: 'visible',
  },
  emergencyModeContainer: {
    backgroundColor: '#b01e26',
    minHeight: 112,
    paddingVertical: 28,
    shadowOpacity: 0.25,
    elevation: 12,
  },
  disabled: {
    backgroundColor: '#c6c6c6',
    shadowOpacity: 0,
    elevation: 0,
  },
  content: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  iconContainer: {
    width: 64,
    height: 64,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
    position: 'relative',
  },
  emergencyBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ffffff',
    paddingHorizontal: 6,
    paddingVertical: 2,
    minWidth: 28,
  },
  emergencyBadgeText: {
    fontSize: 11,
    fontFamily: 'IBMPlexSans-SemiBold',
    fontWeight: '600',
    color: '#da1e28',
    textAlign: 'center',
  },
  textContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  emergencyLabel: {
    fontSize: 24,
    fontFamily: 'IBMPlexSans-SemiBold',
    fontWeight: '600',
    color: '#ffffff',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  callText: {
    fontSize: 18,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#f4f4f4',
  },
  modeText: {
    fontSize: 14,
    fontFamily: 'IBMPlexSans-Regular',
    fontWeight: '400',
    color: '#ffcccc',
    marginTop: 4,
  },
  dialingIndicator: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  dialingText: {
    fontSize: 14,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#da1e28',
  },
  pulseRing: {
    position: 'absolute',
    top: -8,
    left: -8,
    right: -8,
    bottom: -8,
    borderWidth: 2,
    borderColor: '#da1e28',
    opacity: 0.3,
  },
});
