import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  container: {
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: 400,
    maxHeight: '90%',
    paddingVertical: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  emergencyContainer: {
    borderWidth: 2,
    borderColor: '#da1e28',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: 'IBMPlexSans-SemiBold',
    fontWeight: '600',
    color: '#161616',
  },
  emergencyHeaderTitle: {
    color: '#da1e28',
  },
  closeButton: {
    padding: 4,
  },
  emergencyBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fff1f1',
    borderWidth: 1,
    borderColor: '#ffb3ba',
    marginHorizontal: 16,
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  emergencyBannerIcon: {
    marginRight: 8,
    marginTop: 2,
  },
  emergencyBannerText: {
    flex: 1,
    fontSize: 12,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#da1e28',
    lineHeight: 16,
  },
  instructionsContainer: {
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  instructionsText: {
    fontSize: 14,
    fontFamily: 'IBMPlexSans-Regular',
    fontWeight: '400',
    color: '#525252',
    lineHeight: 20,
  },
  inputContainer: {
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#161616',
    marginBottom: 8,
  },
  required: {
    color: '#da1e28',
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: 'IBMPlexSans-Regular',
    fontWeight: '400',
    color: '#161616',
    backgroundColor: '#ffffff',
  },
  addressInput: {
    minHeight: 80,
  },
  notesInput: {
    minHeight: 60,
  },
  quickOptionsContainer: {
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  quickOptionsLabel: {
    fontSize: 12,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#6f6f6f',
    marginBottom: 8,
  },
  quickOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  quickOption: {
    backgroundColor: '#f4f4f4',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginHorizontal: 4,
    marginVertical: 4,
  },
  quickOptionText: {
    fontSize: 12,
    fontFamily: 'IBMPlexSans-Regular',
    fontWeight: '400',
    color: '#161616',
  },
  actionsContainer: {
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  primaryButton: {
    backgroundColor: '#0f62fe',
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 12,
  },
  emergencyButton: {
    backgroundColor: '#da1e28',
  },
  primaryButtonText: {
    fontSize: 16,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#ffffff',
  },
  emergencyButtonText: {
    color: '#ffffff',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#0f62fe',
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontFamily: 'IBMPlexSans-Medium',
    fontWeight: '500',
    color: '#0f62fe',
  },
  helpContainer: {
    paddingHorizontal: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    marginTop: 16,
  },
  helpText: {
    fontSize: 12,
    fontFamily: 'IBMPlexSans-Regular',
    fontWeight: '400',
    color: '#6f6f6f',
    textAlign: 'center',
    lineHeight: 16,
  },
});